<?
// Groot Inlogsysteem versie 2
// Copyright Jorik Berkepas
// Support by helpdesk90@gmail.com (MSN|Email)
// Pagina: forgotpass.php: Wachtwoord opvragen via email
include("config.php");
include("htmltop.php");

if(!isset($_SESSION['user_id'])) {
 if(isset($_POST['submit'])) {
  // Uitvoeren
  if($_POST['user'] != "" AND $_POST['email'] != "") {
   $stmt = $db->stmt_init();
   $stmt->prepare('SELECT `id`, `email` FROM `gebruikers` WHERE `naam` = ?');
   $stmt->bind_param('s', $_POST['user']);
   $stmt->execute();
   $stmt->bind_result($dbid, $dbemail);
   //$sql = "SELECT id,naam,email FROM gebruikers WHERE naam='".$_POST['user']."'";
   //$query = mysql_query($sql);
   //$tellen = mysql_num_rows($query);
   if($stmt->fetch()) {
    // Emailcheck
    //$rij = mysql_fetch_object($query);
    //$dbemail = htmlspecialchars($rij->email);
    //$dbid = htmlspecialchars($rij->id);
    $stmt->close();
    if($dbemail == $_POST['email']) {
     // Wachtwoord wijzigen, met autogenerated, email verzenden
     $actcode = mt_srand((double)microtime()*100000);
     while(strlen($actcode) <= 10) {
      $i = chr(mt_rand (0,255));
      if(eregi("^[a-z0-9]$", $i)) {
       $actcode = $actcode.$i;
      }
     }
     
     $stmt = $db->stmt_init();
     $stmt->prepare('UPDATE `gebruikers` SET `actief` = 0, `actcode` = ? WHERE `id` = ?');
     $stmt->bind_param('si', $actcode, $dbid);
     
     //$sql = "UPDATE gebruikers SET actief=0,actcode='".$actcode."' WHERE id='".$dbid."'";
     //$query = mysql_query($sql);
     if($stmt->execute()) {
      $bericht = "Beste ".$_POST['user'].",\nOp de website ".$sitenaam." heb je aangegeven dat je je wachtwoord bent vergeten.\nOm je wachtwoord te wijzigen, druk je op de link onderaan deze mail, en wijzig je je wachtwoord.\n";
      $bericht .= "Wanneer je niet je wachtwoord wilt wijzigen, klik je op de 2e link, deze zal je account weer activeren, met je huidige wachtwoord.\n\n";
      $bericht .= "WACHTWOORD WIJZIGEN: ".$forgoturl."activeren.php?id=".$dbid."&code=".$actcode." \n\n";
      $bericht .= "WACHTWOORD _NIET_ WIJZIGEN: ".$forgoturl."activeren.php?id=".$dbid."&code=".$actcode."&activeer=true \n\n";
      $bericht .= "** Dit is een automatisch verzonden bericht **";
      $mail = mail($dbemail,"Wachtwoord wijzigen ".$sitenaam,$bericht,"From: ".$sitenaam." <".$sitemail.">");
      if($mail == TRUE) {
       echo "Je account is succesvol gedeactiveerd, en er is een e-mail gestuurd naar je emailadres. In deze e-mail staat een link, wanneer je hierop klikt kom je op een pagina waar je je wachtwoord kunt wijzigen.<br /><a href=\"inloggen.php\">&laquo; Ga naar de inlogpagina</a>";
      }else{
       echo "Er is een fout opgetreden tijdens het verzenden van de mail. Je account blijft gedeactiveerd. Neem contact op met <a href=\"mailto:".$sitemail."\">".$sitemail."</a> om je account te activeren.";
      }
     }else{
      echo "Er is een fout opgetreden tijdens het deactiveren van je account.<br />\n<a href=\"javascript:history.back()\">&laquo; Ga terug</a>";
     }
     $stmt->close();
    }else{
     echo "Het gegeven e-mailadres komt niet overeen met het e-mailadres voor '".$_POST['user']."' in de database.<br />\n<a href=\"javascript:history.back()\">&laquo; Ga terug</a>";
    }
   }else{
    $stmt->close();
    echo "De gebruikersnaam die jij invoerde bestaat niet.<br />\n<a href=\"javascript:history.back()\">&laquo; Ga terug</a>";
   }
  }else{
   echo "Je hebt een veld niet ingevuld. Alle velden zijn verplicht.<br />\n<a href=\"javascript:history.back()\">&laquo; Ga terug</a>";
  }
 }else{
  // Formulier
  ?>
  <form method="post" action="forgotpass.php">
   <table>
    <tr>
     <td>Gebruikersnaam:</td><td><input type="text" name="user" /></td>
    </tr>
    <tr>
     <td>E-mailadres:</td><td><input type="text" name="email" /></td>
    </tr>
    <tr>
     <td></td><td><input type="submit" name="submit" value="Wachtwoord opvragen" /></td>
    </tr>
   </table>
  </form>
  <?
 }
}else{
 echo "Je bent momenteel ingelogd, je kunt nu geen gebruik maken van de 'Wachtwoord vergeten'-functie.<br />\n<a href=\"javascript:history.back();\">&laquo; Ga terug</a>";
}

include("htmlbottom.php");
?>